[build]
target = "./index.html"

[watch]
wath = ["./src"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "./src/root.css", "-o", "assets/styles.css", "--minify"]
